package profiler

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/jnnngs/3270Web/internal/host"
)

// ProberHost is the subset of host.Host that Probe needs. It is satisfied by
// *host.S3270, *host.MockHost, and *host.GoSampleAppHost. Tests use
// host.MockHost directly via its QueryResponses map.
type ProberHost interface {
	IsConnected() bool
	UpdateScreen() error
	GetScreen() *host.Screen
	Query(arg string) (string, error)
}

// ConnectTimingSource is an optional interface that lets Probe pick up the
// elapsed time of the most recent connect. *host.S3270 implements it.
type ConnectTimingSource interface {
	LastConnectDuration() time.Duration
}

// ProbeOptions tunes Probe behaviour. Zero value is safe.
type ProbeOptions struct {
	// PerActionTimeout bounds each individual s3270 Query (default 3s).
	PerActionTimeout time.Duration
	// CollectRaw, when true, includes raw Query responses in
	// CompatibilityProfile.Raw, keyed by query name.
	CollectRaw bool
	// INDFileProbe, when true, sends "IND$FILE ?" to the host and inspects
	// the response. This is mildly destructive (it types into the current
	// session) and always issues Clear/PA1 to restore. Default false.
	INDFileProbe bool
	// Tool and Version populate ProfilerMeta. If empty, "3270Web"/"dev"
	// defaults are used.
	Tool    string
	Version string
	// Host and Port populate HostIdentity. If empty, Probe attempts to read
	// them from Query(Host); if that fails, they remain empty.
	Host string
	Port int
	// TLS marks the host as TLS-protected (callers set this from session
	// state; Probe cannot reliably infer it).
	TLS bool
	// RunID overrides the autogenerated run identifier (testing aid).
	RunID string
	// Now overrides time.Now (testing aid).
	Now func() time.Time
}

const defaultPerActionTimeout = 3 * time.Second

// Probe runs a sequence of read-only Query actions against h and returns a
// populated CompatibilityProfile. Queries that fail or return empty are
// recorded in Capabilities.Unknown so callers can spot environment
// divergence; only "session not connected" and ctx cancellation produce a
// hard error.
func Probe(ctx context.Context, h ProberHost, opts ProbeOptions) (*CompatibilityProfile, error) {
	if h == nil {
		return nil, fmt.Errorf("profiler: host is nil")
	}
	if !h.IsConnected() {
		return nil, fmt.Errorf("profiler: host is not connected")
	}
	if opts.PerActionTimeout <= 0 {
		opts.PerActionTimeout = defaultPerActionTimeout
	}
	if opts.Tool == "" {
		opts.Tool = "3270Web"
	}
	if opts.Version == "" {
		opts.Version = "dev"
	}
	now := time.Now
	if opts.Now != nil {
		now = opts.Now
	}
	runID := strings.TrimSpace(opts.RunID)
	if runID == "" {
		runID = randomRunID()
	}

	probeStart := now()
	profile := &CompatibilityProfile{
		SchemaVersion: SchemaVersion,
		RunID:         runID,
		Timestamp:     probeStart.UTC(),
		Profiler:      ProfilerMeta{Tool: opts.Tool, Version: opts.Version},
		// Host identity is populated by Query(Host) when the host answers; we
		// fall back to opts after the probe so the negotiated identity (the
		// stable diff key across environments) takes precedence.
		Capabilities: CapabilityProfile{INDFile: TriUnknown},
	}
	if opts.TLS {
		profile.Host.TLS = true
	}
	if opts.CollectRaw {
		profile.Raw = make(map[string]string)
	}

	// Sequence of Query actions. Failure or empty response degrades the
	// corresponding fields to zero and appends the query name to
	// Capabilities.Unknown.
	for _, q := range probeSequence() {
		if ctx.Err() != nil {
			return nil, ctx.Err()
		}
		resp, err := queryWithTimeout(ctx, h, q.name, opts.PerActionTimeout)
		if err != nil || strings.TrimSpace(resp) == "" {
			profile.Capabilities.Unknown = appendUnique(profile.Capabilities.Unknown, q.name)
			continue
		}
		if profile.Raw != nil {
			profile.Raw[q.name] = resp
		}
		q.apply(profile, resp)
	}

	// First-screen capture + timing. Always best-effort.
	firstScreenStart := now()
	if err := h.UpdateScreen(); err == nil {
		screen := h.GetScreen()
		if screen != nil {
			profile.Timing.FirstScreenMS = now().Sub(firstScreenStart).Milliseconds()
			applyScreenFingerprint(profile, screen)
			applyStatusFallbacks(profile, screen)
		}
	}

	// Connect duration: if the host exposes it, prefer that (it covers the
	// actual TCP+TN3270 negotiation, not just the probe window).
	if cts, ok := h.(ConnectTimingSource); ok {
		if d := cts.LastConnectDuration(); d > 0 {
			profile.Timing.ConnectMS = d.Milliseconds()
		}
	}

	// IND$FILE probe (opt-in, semi-destructive).
	if opts.INDFileProbe {
		profile.Capabilities.INDFile = probeINDFile(ctx, h, opts.PerActionTimeout)
	}

	// Fall back to caller-supplied identity if the host did not answer
	// Query(Host). The negotiated identity always wins when present.
	if profile.Host.Host == "" {
		profile.Host.Host = opts.Host
	}
	if profile.Host.Port == 0 {
		profile.Host.Port = opts.Port
	}

	// Sort Unknown for deterministic output.
	sort.Strings(profile.Capabilities.Unknown)
	return profile, nil
}

type queryStep struct {
	name  string
	apply func(p *CompatibilityProfile, response string)
}

func probeSequence() []queryStep {
	return []queryStep{
		{"Host", applyQueryHost},
		{"ConnectionState", applyQueryConnectionState},
		{"Bind", applyQueryBind},
		{"Cursor", applyQueryCursor},
		{"Model", applyQueryModel},
		{"BindPluName", applyQueryBindPluName},
		{"Tn3270eFunctions", applyQueryTn3270eFunctions},
		{"ScreenCurSize", applyQueryScreenCurSize},
	}
}

func queryWithTimeout(ctx context.Context, h ProberHost, arg string, timeout time.Duration) (string, error) {
	type result struct {
		resp string
		err  error
	}
	ch := make(chan result, 1)
	go func() {
		resp, err := h.Query(arg)
		ch <- result{resp: resp, err: err}
	}()
	select {
	case r := <-ch:
		return r.resp, r.err
	case <-time.After(timeout):
		return "", fmt.Errorf("query %s timed out after %s", arg, timeout)
	case <-ctx.Done():
		return "", ctx.Err()
	}
}

func applyScreenFingerprint(p *CompatibilityProfile, s *host.Screen) {
	if s == nil {
		return
	}
	text := s.Text()
	preview := normaliseScreenText(text)
	if preview == "" {
		return
	}
	sum := sha256.Sum256([]byte(preview))
	p.Host.BannerSignature = hex.EncodeToString(sum[:])
	if len(preview) > 240 {
		p.Host.BannerPreview = preview[:240]
	} else {
		p.Host.BannerPreview = preview
	}
}

func applyStatusFallbacks(p *CompatibilityProfile, s *host.Screen) {
	if s == nil {
		return
	}
	if p.Device.Rows == 0 || p.Device.Cols == 0 {
		if rows, cols, ok := s.StatusDimensions(); ok {
			if p.Device.Rows == 0 {
				p.Device.Rows = rows
			}
			if p.Device.Cols == 0 {
				p.Device.Cols = cols
			}
		}
	}
	if p.Device.TerminalType == "" {
		if model, ok := s.StatusModel(); ok && strings.TrimSpace(model) != "" {
			p.Device.TerminalType = "Model-" + strings.TrimSpace(model)
		}
	}
	if locked, ok := s.StatusKeyboardLocked(); ok && !locked {
		// Keyboard already unlocked at first screen capture — measure
		// from probe start as a coarse upper bound. Callers that want
		// fine-grained timing should subscribe to status events.
		if p.Timing.KeyboardUnlockMS == 0 {
			p.Timing.KeyboardUnlockMS = p.Timing.FirstScreenMS
		}
	}
}

func appendUnique(s []string, v string) []string {
	for _, existing := range s {
		if existing == v {
			return s
		}
	}
	return append(s, v)
}

func randomRunID() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return fmt.Sprintf("run-%d", time.Now().UnixNano())
	}
	return "run-" + hex.EncodeToString(b[:])
}

// probeINDFile is intentionally minimal in the first slice: it returns
// TriUnknown because the safe round-trip (type-and-restore) requires
// additional host interaction beyond the ProberHost surface. Future slices
// can broaden this to actually send the probe via host.SendKey/SubmitScreen.
// We accept the conservative "unknown" answer so the Probe contract stays
// strictly read-only.
func probeINDFile(ctx context.Context, h ProberHost, timeout time.Duration) TriState {
	_ = ctx
	_ = h
	_ = timeout
	return TriUnknown
}

// normaliseScreenText collapses runs of whitespace, strips control chars, and
// trims surrounding whitespace so a banner fingerprint is stable across
// trivial cursor or padding differences between hosts.
func normaliseScreenText(text string) string {
	var b strings.Builder
	b.Grow(len(text))
	prevSpace := true
	for _, r := range text {
		switch {
		case r == 0:
			r = ' '
		case r < 0x20 || r == 0x7f:
			r = ' '
		case r > 0x7e:
			r = '?' // ASCII fold so signatures don't drift on codepoint quirks
		}
		if r == ' ' {
			if prevSpace {
				continue
			}
			prevSpace = true
		} else {
			prevSpace = false
		}
		b.WriteRune(r)
	}
	return strings.TrimSpace(b.String())
}
